name: E2E site testing

on:
  push:
    tags:
      - v*
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  e2e-current:
    name: e2e current latest branch
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-ver: ["3.11", "3.12"]
        os: [ubuntu-latest]
        # os: [self-hosted-arm64, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-ver }}

      - name: header
        run: |
          echo -e "\e[1;33m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\e[0m
          \e[1;33m┃\e[0m \e[1;36m E2E Test \e[0m \e[1;33m┃\e[0m
          \e[1;33m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\e[0m"

      - name: install frappe from current commit
        run: |
          cd ..
          python -m pip install --upgrade ./Frappe-Manager

      - name: frappe version
        run: fm --version

      - name: e2e run
        timeout-minutes: 20
        working-directory: test
        run: |
          ./e2e_test.sh

      - name: cleanup
        if: always()
        run: |
          python -m pip uninstall -y frappe-manager
          sudo rm -rf ~/frappe
