name: E2E on push event

on:
  push:
    tags:
      - v*
    branches:
      - main
      - develop
      - feat-add-e2e-test # TODO(user): remove it
  workflow_dispatch:

jobs:
  e2e-current:
    name: e2e current latest branch
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-ver: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-ver }}

      - name: install frappe from v0.9.0
        run: |
          cd /tmp
          python -m pip install -U git+https://github.com/rtCamp/Frappe-Manager.git@v0.9.0

      - name: frappe version
        run: fm --version

